import httpx
from server.utils.logger import logger


async def create_github_pr(
    owner: str,
    repo: str,
    branch_name: str,
    error_message: str,
    token: str,
    base: str = "main",
) -> str:
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    body = f"""This PR was automatically generated by the AI debugging system.

**Original Error:**
```
{error_message}
```

**Changes:**
- Fixed frontend runtime error
- Added defensive handling
- Validated build successfully

> Review carefully before merging."""

    payload = {
        "title": "fix: AI Generated Frontend Fix",
        "head": branch_name,
        "base": base,
        "body": body,
        "draft": True,
    }

    async with httpx.AsyncClient() as client:
        response = await client.post(url, json=payload, headers=headers)
        response.raise_for_status()

        data = response.json()
        pr_url = data.get("html_url")
        if not pr_url:
            raise RuntimeError(
                f"GitHub PR created but response missing html_url. "
                f"Response: {data}"
            )

        logger.info(f"[github] PR created: {pr_url}")
        return pr_url
